INSERT INTO ACCOUNT(ID,PRENOM,NOM,AMOUNT) VALUES (1,'Pierre','Jean','100.00');
INSERT INTO ACCOUNT(ID,PRENOM,NOM,AMOUNT) VALUES (2,'Pierre','Jean','10.00');
INSERT INTO ACCOUNT(ID,PRENOM,NOM,AMOUNT) VALUES (3,'Jean','Pierre','200.00');
INSERT INTO ACCOUNT(ID,PRENOM,NOM,AMOUNT) VALUES (4,'NiJean','NiPierre','100000.00');
