INSERT INTO ACCOUNT(ID,CLIENT_ID,AMOUNT) VALUES (1,1,'100.00');
INSERT INTO ACCOUNT(ID,CLIENT_ID,AMOUNT) VALUES (2,2,'10.00');
INSERT INTO ACCOUNT(ID,CLIENT_ID,AMOUNT) VALUES (3,3,'200.00');
INSERT INTO ACCOUNT(ID,CLIENT_ID,AMOUNT) VALUES (4,4,'100000.00');
INSERT INTO CLIENT(ID,PRENOM,NOM) VALUES (1,'Pierre','Jean');
INSERT INTO ACCOUNT(ID,PRENOM,NOM) VALUES (2,'Pierre','Jacques');
INSERT INTO ACCOUNT(ID,PRENOM,NOM) VALUES (3,'Jacques','Lang');
INSERT INTO ACCOUNT(ID,PRENOM,NOM) VALUES (4,'Lang','Debois');